export const CLI_OPTIONS = {
  index: { type: 'string' },
  context: { type: 'string' },
  help: { type: 'boolean', short: 'h' },
  version: { type: 'boolean', short: 'v' },
  skill: { type: 'boolean' },
  global: { type: 'boolean' },
  yes: { type: 'boolean' },
  n: { type: 'string' },
  'min-score': { type: 'string' },
  all: { type: 'boolean' },
  full: { type: 'boolean' },
  csv: { type: 'boolean' },
  md: { type: 'boolean' },
  xml: { type: 'boolean' },
  files: { type: 'boolean' },
  json: { type: 'boolean' },
  explain: { type: 'boolean' },
  collection: { type: 'string', short: 'c', multiple: true },
  name: { type: 'string' },
  mask: { type: 'string' },
  force: { type: 'boolean', short: 'f' },
  pull: { type: 'boolean' },
  refresh: { type: 'boolean' },
  l: { type: 'string' },
  from: { type: 'string' },
  'max-bytes': { type: 'string' },
  'line-numbers': { type: 'boolean' },
  'candidate-limit': { type: 'string', short: 'C' },
  intent: { type: 'string' },
  http: { type: 'boolean' },
  daemon: { type: 'boolean' },
  port: { type: 'string' },
} as const;
